# Generated by Django 2.2.7 on 2019-11-20 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cancion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_cancion', models.CharField(max_length=30)),
                ('desc_cancion', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Cancion',
                'verbose_name_plural': 'Canciones',
            },
        ),
    ]
